# Файл docker-compose.yml
version: '2.4' # Указание версии 2.4 (можно и 3.x, но синтаксис volumes останется)

# Перечень volume
volumes:
  pg_data:
  static:

    # Явно объявляем сеть
networks:
  django-network:
    driver: bridge # Драйвер bridge - стандартный для коммуникации между контейнерами

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      # Подключаем сервис к сети
      - django-network

  backend:
    build: ./backend/
    env_file: .env
    # Тут подключаем volume к backend
    volumes:
      - static:/backend_static
    depends_on:
      - db
    networks:
      # Подключаем сервис к сети
      - django-network

  frontend:
    env_file: .env
    build: ./frontend/
    volumes:
      - static:/frontend_static
    command: cp -r /app/build/. /frontend_static/
    networks:
      # Подключаем сервис к сети
      - django-network

  gateway:
    build: ./gateway/
    # А тут подключаем volume со статикой к gateway
    volumes:
      - static:/staticfiles
    ports:
      - 8000:80
    depends_on:
      # Говорим Compose, что gateway зависит от backend
      - backend
    networks:
      # Подключаем сервис к сети. Это ключевое исправление!
      - django-network
